"""Integrate generated game assets into index.html"""

import re

HTML_PATH = r"D:\0.技師案子-本地作業\APP\blocktopia\index.html"
ASSETS_DIR = r"D:\0.技師案子-本地作業\APP\blocktopia\assets"

# Read base64 data
assets = {}
for name in ["mascot", "trophy", "crown", "medal_gold", "medal_silver", "medal_bronze"]:
    with open(f"{ASSETS_DIR}/{name}.b64") as f:
        assets[name] = f.read().strip()

# Read HTML
with open(HTML_PATH, encoding="utf-8") as f:
    html = f.read()

# ═══════════════════════════════════════════
# 1. Insert GAME_ASSETS constant + preloader
# ═══════════════════════════════════════════
# Insert after: const SP = { BOMB:11, ... };
anchor = "const SP = { BOMB:11, RAINBOW:12, LIGHTNING:13,\n             STONE:20, ICE1:21, ICE2:22, LOCKED:23 };"
assert anchor in html, "Anchor not found for GAME_ASSETS insertion"

asset_code = f"""
// ============================================================
//  PREMIUM GAME ASSETS (Generated by Nano Banana Pro)
// ============================================================
const GAME_ASSETS = {{
  mascot: "{assets['mascot']}",
  trophy: "{assets['trophy']}",
  crown: "{assets['crown']}",
  medalGold: "{assets['medal_gold']}",
  medalSilver: "{assets['medal_silver']}",
  medalBronze: "{assets['medal_bronze']}",
}};

// Preload all asset images
const _assetImages = {{}};
for (const [key, src] of Object.entries(GAME_ASSETS)) {{
  const img = new Image();
  img.src = src;
  _assetImages[key] = img;
}}
"""

html = html.replace(anchor, anchor + "\n" + asset_code)

# ═══════════════════════════════════════════
# 2. Replace menu mascot (canvas-drawn block face → premium image)
# ═══════════════════════════════════════════
old_mascot = """  // Cute mascot — simple block face with blinking
  const mascotY = cy - 160 - (1-e)*40;
  const mascotS = 48;
  ctx.globalAlpha = e;
  drawBlock(cx-mascotS/2, mascotY-mascotS/2, mascotS, 6);
  // Eyes (blink every ~3s)
  const blinkPhase = (now % 3000) < 150;
  ctx.fillStyle = '#fff';
  if (blinkPhase) {
    ctx.fillRect(cx-12, mascotY-4, 8, 2);
    ctx.fillRect(cx+4, mascotY-4, 8, 2);
  } else {
    ctx.beginPath(); ctx.arc(cx-8, mascotY-3, 3, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(cx+8, mascotY-3, 3, 0, Math.PI*2); ctx.fill();
  }
  // Smile
  ctx.strokeStyle = '#fff';
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.arc(cx, mascotY+4, 8, 0.1*Math.PI, 0.9*Math.PI);
  ctx.stroke();"""

new_mascot = """  // Premium mascot image with floating animation
  const mascotY = cy - 160 - (1-e)*40 + Math.sin(now*0.002)*6;
  const mascotS = 90;
  ctx.globalAlpha = e;
  const mi = _assetImages.mascot;
  if (mi && mi.complete && mi.naturalWidth > 0) {
    // Glow behind mascot
    ctx.shadowColor = 'rgba(120,100,255,0.35)';
    ctx.shadowBlur = 25 + Math.sin(now*0.003)*8;
    ctx.drawImage(mi, cx-mascotS/2, mascotY-mascotS/2, mascotS, mascotS);
    ctx.shadowBlur = 0;
  } else {
    // Fallback: simple block face
    drawBlock(cx-24, mascotY-24, 48, 6);
    ctx.fillStyle = '#fff';
    ctx.beginPath(); ctx.arc(cx-8, mascotY-3, 3, 0, Math.PI*2); ctx.fill();
    ctx.beginPath(); ctx.arc(cx+8, mascotY-3, 3, 0, Math.PI*2); ctx.fill();
  }"""

assert old_mascot in html, "Old mascot code not found"
html = html.replace(old_mascot, new_mascot)

# ═══════════════════════════════════════════
# 3. Replace _drawCrown with image version
# ═══════════════════════════════════════════
old_crown = """function _drawCrown(x, y, s) {
  // Simple canvas crown
  ctx.fillStyle = '#FFD700';
  ctx.shadowColor = 'rgba(255,215,0,0.5)'; ctx.shadowBlur = 8;
  ctx.beginPath();
  ctx.moveTo(x-s, y+s*0.4);
  ctx.lineTo(x-s, y-s*0.3);
  ctx.lineTo(x-s*0.5, y+s*0.1);
  ctx.lineTo(x, y-s*0.6);
  ctx.lineTo(x+s*0.5, y+s*0.1);
  ctx.lineTo(x+s, y-s*0.3);
  ctx.lineTo(x+s, y+s*0.4);
  ctx.closePath();
  ctx.fill();
  ctx.shadowBlur = 0;
  // Gems
  ctx.fillStyle = '#FF4444';
  ctx.beginPath(); ctx.arc(x, y-s*0.15, s*0.12, 0, Math.PI*2); ctx.fill();
  ctx.fillStyle = '#44AAFF';
  ctx.beginPath(); ctx.arc(x-s*0.5, y+s*0.05, s*0.08, 0, Math.PI*2); ctx.fill();
  ctx.beginPath(); ctx.arc(x+s*0.5, y+s*0.05, s*0.08, 0, Math.PI*2); ctx.fill();
}"""

new_crown = """function _drawCrown(x, y, s) {
  const ci = _assetImages.crown;
  const sz = s * 3.5;
  if (ci && ci.complete && ci.naturalWidth > 0) {
    ctx.shadowColor = 'rgba(255,215,0,0.5)'; ctx.shadowBlur = 10;
    ctx.drawImage(ci, x-sz/2, y-sz*0.7, sz, sz);
    ctx.shadowBlur = 0;
  } else {
    // Fallback: simple canvas crown
    ctx.fillStyle = '#FFD700';
    ctx.shadowColor = 'rgba(255,215,0,0.5)'; ctx.shadowBlur = 8;
    ctx.beginPath();
    ctx.moveTo(x-s, y+s*0.4); ctx.lineTo(x-s, y-s*0.3);
    ctx.lineTo(x-s*0.5, y+s*0.1); ctx.lineTo(x, y-s*0.6);
    ctx.lineTo(x+s*0.5, y+s*0.1); ctx.lineTo(x+s, y-s*0.3);
    ctx.lineTo(x+s, y+s*0.4); ctx.closePath(); ctx.fill();
    ctx.shadowBlur = 0;
  }
}"""

assert old_crown in html, "Old crown code not found"
html = html.replace(old_crown, new_crown)

# ═══════════════════════════════════════════
# 4. Replace _drawMedalBadge with image version
# ═══════════════════════════════════════════
old_medal = """function _drawMedalBadge(x, y, r, rank, color, darkColor) {
  // 3D medal with ribbon
  // Ribbon
  ctx.fillStyle = rank===0?'#CC0000':rank===1?'#3355AA':'#884422';
  ctx.beginPath();
  ctx.moveTo(x-r*0.4, y-r*0.2);
  ctx.lineTo(x-r*0.7, y-r*1.2);
  ctx.lineTo(x-r*0.1, y-r*0.6);
  ctx.closePath(); ctx.fill();
  ctx.beginPath();
  ctx.moveTo(x+r*0.4, y-r*0.2);
  ctx.lineTo(x+r*0.7, y-r*1.2);
  ctx.lineTo(x+r*0.1, y-r*0.6);
  ctx.closePath(); ctx.fill();
  // Medal circle
  const mg = ctx.createRadialGradient(x-r*0.25, y-r*0.25, 0, x, y, r);
  mg.addColorStop(0, '#fff');
  mg.addColorStop(0.3, color);
  mg.addColorStop(1, darkColor);
  ctx.fillStyle = mg;
  ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI*2); ctx.fill();
  // Inner ring
  ctx.strokeStyle = 'rgba(255,255,255,0.3)';
  ctx.lineWidth = 1.5;
  ctx.beginPath(); ctx.arc(x, y, r*0.75, 0, Math.PI*2); ctx.stroke();
  // Number
  ctx.fillStyle = darkColor;
  ctx.font = 'bold '+Math.round(r*0.9)+'px "Nunito",sans-serif';
  ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
  ctx.fillText(String(rank+1), x, y+1);
}"""

new_medal = """function _drawMedalBadge(x, y, r, rank, color, darkColor) {
  const medalImgs = [_assetImages.medalGold, _assetImages.medalSilver, _assetImages.medalBronze];
  const mi = medalImgs[rank];
  const sz = r * 2.8;
  if (mi && mi.complete && mi.naturalWidth > 0) {
    ctx.drawImage(mi, x-sz/2, y-sz/2, sz, sz);
  } else {
    // Fallback: canvas medal
    const mg = ctx.createRadialGradient(x-r*0.25, y-r*0.25, 0, x, y, r);
    mg.addColorStop(0, '#fff'); mg.addColorStop(0.3, color); mg.addColorStop(1, darkColor);
    ctx.fillStyle = mg;
    ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI*2); ctx.fill();
    ctx.fillStyle = darkColor;
    ctx.font = 'bold '+Math.round(r*0.9)+'px "Nunito",sans-serif';
    ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.fillText(String(rank+1), x, y+1);
  }
}"""

assert old_medal in html, "Old medal code not found"
html = html.replace(old_medal, new_medal)

# ═══════════════════════════════════════════
# 5. Replace leaderboard empty state with trophy image
# ═══════════════════════════════════════════
old_empty = """    // Empty state
    const emCy = curY + 80;
    // Big trophy with glow
    const gp = 0.4 + Math.sin(now*0.002)*0.3;
    ctx.shadowColor = 'rgba(255,200,60,'+gp+')'; ctx.shadowBlur = 30;
    ctx.font = '60px serif'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    ctx.fillText('\\uD83C\\uDFC6', cx, emCy);
    ctx.shadowBlur = 0;"""

new_empty = """    // Empty state — premium trophy
    const emCy = curY + 80;
    const ti = _assetImages.trophy;
    const gp = 0.4 + Math.sin(now*0.002)*0.3;
    if (ti && ti.complete && ti.naturalWidth > 0) {
      const tsz = 100;
      ctx.shadowColor = 'rgba(255,200,60,'+gp+')'; ctx.shadowBlur = 30;
      ctx.drawImage(ti, cx-tsz/2, emCy-tsz/2, tsz, tsz);
      ctx.shadowBlur = 0;
    } else {
      ctx.shadowColor = 'rgba(255,200,60,'+gp+')'; ctx.shadowBlur = 30;
      ctx.font = '60px serif'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
      ctx.fillText('\\uD83C\\uDFC6', cx, emCy);
      ctx.shadowBlur = 0;
    }"""

assert old_empty in html, "Old empty state code not found"
html = html.replace(old_empty, new_empty)

# ═══════════════════════════════════════════
# 6. Add mascot to Game Over screen (above "遊戲結束!")
# ═══════════════════════════════════════════
old_go_title = """  // Cute title
  let cy = py+45;
  ctx.shadowColor = 'rgba(255,100,100,0.3)'; ctx.shadowBlur = 15;
  ctx.fillStyle = '#fff';
  ctx.font = 'bold 28px '+CUTE;
  ctx.fillText('\\uD83D\\uDE35 \\u904A\\u6232\\u7D50\\u675F!', cx, cy);
  ctx.shadowBlur = 0;
  ctx.fillStyle = '#8899AA';
  ctx.font = '600 14px '+CUTE;
  ctx.fillText('Game Over', cx, cy+26);"""

new_go_title = """  // Mascot (sad/dizzy) + Cute title
  const goMi = _assetImages.mascot;
  let cy = py+45;
  if (goMi && goMi.complete && goMi.naturalWidth > 0) {
    const ms = 56;
    ctx.globalAlpha = 0.7;
    ctx.save();
    ctx.translate(cx, cy-8);
    ctx.rotate(Math.sin(now*0.004)*0.08);  // Gentle wobble
    ctx.drawImage(goMi, -ms/2, -ms/2, ms, ms);
    ctx.restore();
    ctx.globalAlpha = 1;
    cy += 36;
  }
  ctx.shadowColor = 'rgba(255,100,100,0.3)'; ctx.shadowBlur = 15;
  ctx.fillStyle = '#fff';
  ctx.font = 'bold 26px '+CUTE;
  ctx.fillText('\\u904A\\u6232\\u7D50\\u675F!', cx, cy);
  ctx.shadowBlur = 0;
  ctx.fillStyle = '#8899AA';
  ctx.font = '600 13px '+CUTE;
  ctx.fillText('Game Over', cx, cy+22);"""

assert old_go_title in html, "Old game over title code not found"
html = html.replace(old_go_title, new_go_title)

# ═══════════════════════════════════════════
# 7. Add trophy image to leaderboard header (beside title)
# ═══════════════════════════════════════════
old_header_title = """  // Title with gold shimmer
  const shimmer = 0.85 + Math.sin(now*0.002)*0.15;
  ctx.fillStyle = 'rgba(255,215,0,'+shimmer+')';
  ctx.font = 'bold 20px '+F; ctx.textAlign = 'center';
  ctx.shadowColor = 'rgba(255,200,60,0.4)'; ctx.shadowBlur = 12;
  ctx.fillText('\\uD83C\\uDFC6 \\u6392\\u884C\\u699C', cx, hdrH/2);
  ctx.shadowBlur = 0;"""

new_header_title = """  // Title with gold shimmer + trophy icon
  const shimmer = 0.85 + Math.sin(now*0.002)*0.15;
  const hti = _assetImages.trophy;
  if (hti && hti.complete && hti.naturalWidth > 0) {
    const ts = 32;
    ctx.shadowColor = 'rgba(255,200,60,0.5)'; ctx.shadowBlur = 10;
    ctx.drawImage(hti, cx-80, hdrH/2-ts/2, ts, ts);
    ctx.shadowBlur = 0;
  }
  ctx.fillStyle = 'rgba(255,215,0,'+shimmer+')';
  ctx.font = 'bold 20px '+F; ctx.textAlign = 'center';
  ctx.shadowColor = 'rgba(255,200,60,0.4)'; ctx.shadowBlur = 12;
  ctx.fillText('\\u6392\\u884C\\u699C', cx+4, hdrH/2);
  ctx.shadowBlur = 0;"""

assert old_header_title in html, "Old header title code not found"
html = html.replace(old_header_title, new_header_title)

# ═══════════════════════════════════════════
# 8. Adjust Game Over panel height to accommodate mascot
# ═══════════════════════════════════════════
html = html.replace(
    "const pw=300, ph=420, px=cx-pw/2, py=(L.h-ph)/2-10;",
    "const pw=300, ph=460, px=cx-pw/2, py=(L.h-ph)/2-10;",
)

# Write
with open(HTML_PATH, "w", encoding="utf-8") as f:
    f.write(html)

print("All integrations complete!")
print(f"  - GAME_ASSETS constant + preloader added")
print(f"  - Menu mascot: premium image with floating animation + glow")
print(f"  - Leaderboard crown: premium image")
print(f"  - Leaderboard medals: premium gold/silver/bronze images")
print(f"  - Leaderboard empty: premium trophy image")
print(f"  - Leaderboard header: trophy icon beside title")
print(f"  - Game Over: mascot with wobble animation")
print(f"  - Game Over panel: taller for mascot")
